### ISSUE TITLE
C++ assistant creates bulk annoying content

### ISSUE THREAD

**Issue by hroncok** [devassistant/devassistant-assistants-fedora#14]
Assistant should help me, not introduce more stuff to annoy me. C++ assistant creates some classes I won't use and README content to delete.

While this would be a good "How to code in C++" assistant, it is absolutely useless for new C++ projects. Filtering garbage form useful content is more time consuming than creating the project from scratch without DA.
- Remove all example garbage
- Keep the assistant useful and ready to use

I think that all this also covers the C assistant.

**Comment by bkabrda** [comment]
CC @phracek.

**Comment by phracek** [comment]
Well, reason of garbage was to help beginners with writing first C/C++ programs.
I have already used that in case of tiff debugging some segfault. I have generated the basic code
and make some 'easy modifycation' and my program was working properly at first time.

This was a reason of the all garbage.

Also I have some references that it helps users with some basic c/c++ stuff.

**Comment by hroncok** [comment]
Depending on what we want this assistant to do. If we want to teach C++, then OK. But I believed we want to make developers' lives easier. Depending on decision described in https://lists.fedoraproject.org/pipermail/devassistant/2014-February/000018.html we might not need to solve this and later there can be more c++ assistants for different purposes.

I have a talk this weekend about DevAssistent, on Prague InstallFest - I wanted to focus mostly on our students (where programming is done mostly by C/C++) - to show them how DevAssistant helps them kickstart their school projects. However, this amount of garbage makes this assistant useless for them and therefore I'll have to present some different assistants instead :(

**Comment by phracek** [comment]
Of course not. I don't think that we want to teach C/C++.

But without any C/C++ source codes I am not able to executed and create any autotools project.
This was a second reason.
But we can create a really simple C/C++ program for that case.
