### ISSUE TITLE
.spec files should be modified to use user's name and current date

### ISSUE THREAD

**Issue by jwakely** [devassistant/devassistant-assistants-fedora#20]
The `files/crt/c/cdevelopmenttool.spec` file and the C++ equivalent have this changelog:

```
* Fri Mar 15 2013 UserName
- first Version
```

When the project is created the date and name should be replaced with more meaningful values. On POSIX platforms the user's name can be obtained with `pwd.getpwuid(posix.getuid()).pw_gecos`

**Comment by phracek** [comment]
Jonathan thanks for the bug and fix as well.
