### ISSUE TITLE
root password needed to build RPMs from C and C++ projects

### ISSUE THREAD

**Issue by jwakely** [devassistant/devassistant-assistants-fedora#23]
When using `-b` to build an RPM `cpp.yaml` unconditionally runs `yum-buildep` as root.

If all the BuildRequires packages are already installed this is unnecessary, but the user has to enter the root passwd or the build fails.

The user might not know the root password, and it isn't needed to run `rpmbuild`, so it should only be requested when there are missing packages.  The BuildRequires can be queried with:

```
rpmspec -q --buildrequires foobar.spec
```

and each package can be checked for.

**Comment by bkabrda** [comment]
Fixed in https://github.com/bkabrda/devassistant-assistants-fedora/pull/32, closing.
