### ISSUE TITLE
Reveal.js assistant

### ISSUE THREAD

**Issue by tradej** [devassistant/devassistant-assistants-fedora#45]
Hi. We could use a Reveal.js assistant as it is simple enough to make, and would be of a great benefit. Additionally, it could deploy to OpenShift's Reveal.js cartridge (requiring addition of OS helpers in the core, presumably).

**Comment by hroncok** [comment]
Why not  make it a dap and upload it to Dapi?

**Comment by tradej** [comment]
Of course. I just posted this here so that we have a tracker.

**Comment by tradej** [comment]
Assistant lives in [tradej/revealjs-assistant](https://github.com/tradej/revealjs-assistant) and has been pushed to DAPI.
