### ISSUE TITLE
dap related assistants

### ISSUE THREAD

**Issue by hroncok** [devassistant/devassistant-assistants-fedora#51]
In order to promote dap index, we have to provide a way to easily create an assistant.

I suggest a crt assistant that would accept switches like --crt --mod --prep --snippet, etc. and would create a repository like this one https://github.com/3DprintFIT/dap-openscad

And then mod assistant, that would do this:

https://github.com/3DprintFIT/dap-openscad/blob/master/dapgen.sh

(in a more sophisticated way)

**Comment by bkabrda** [comment]
+1. My thoughts exactly.

**Comment by hroncok** [comment]
Should we implement the version getting in core, or guess it with bash directly form the assistant?

**Comment by bkabrda** [comment]
Ugh, I didn't notice that second part... So you actually want `dap` packing to be an assistant? I was thinking that it should rather be core functionality, as in `da pkg pack`. I consider `pack` closer to `lint` than to `da create assistant --crt --mod foo`, but that may just be my feeling... Do you have any specific reasons why to implement packing as assistant?

**Comment by hroncok** [comment]
not really

**Comment by hroncok** [comment]
https://github.com/devassistant/dap-dap
