### ISSUE TITLE
python/gtk3 assistent does not work

### ISSUE THREAD

**Issue by xsuchy** [devassistant/devassistant-assistants-fedora#54]
On first run, it succeded, but the project directory is empty.
On second run, it fails with:

```
Creating GTK+ 3 project test3 in /tmp ...
cp -r /home/msuchy/projects/devassistant-assistants-fedora/files/crt/python/gtk3/. "test3"
On branch master
nothing to commit, working directory clean
```

**Comment by phracek** [comment]
I will look on that.

**Comment by phracek** [comment]
phracek@kiasportyw: ~$ ./da.py crt python gtk3 -n test3
INFO: Creating GTK+ 3 project test3 in . ...
[devassistant]$ cp -r /home/phracek/work/programming/devassistant/devassistant/data/files/crt/python/gtk3/. "test3"
INFO: GTK+ 3 project test3 in . has been created.
INFO: To run the application use: ./template-gui.py
phracek@kiasportyw: ~$ ls test3/
firstWindow.py  firstWindow.pyc  logger.py  template-gui.glade  template-gui.py
phracek@kiasportyw: ~$ ./da.py crt python gtk3 -n test3
ERROR: Directory "test3" already exists, can't proceed
phracek@kiasportyw: ~$ 

It seems that it is working.

Could you please provide a reproducer?
How can I simulate it?

**Comment by xsuchy** [comment]
```
./da-gui
  Create Project -> Python -> Python GTK+ 3
  Project name: test3
  Create in: /tmp
  Run
```

Results:
- Directory /tmp/test3 exist, but it is empty
- Directory ~/test3/ exist (but should not exist) and contains populated project.

**Comment by tradej** [comment]
Fixed in https://github.com/devassistant/dap-python/commit/5e0c86828a0abbe1e281d45c0394c36473e01068
