### ISSUE TITLE
django assistant broken on Fedora 21

### ISSUE THREAD

**Issue by rosskarchner** [devassistant/devassistant-assistants-fedora#57]
Here's what happens if I create a Django project, using python 3 and virtualenv, on Fedora 21 Alpha:

![da](https://cloud.githubusercontent.com/assets/235397/4551363/533448d6-4e70-11e4-817f-c1685e7b3a8a.png)

I suspect the problem is that F21 uses python 3.4,  where virtualenv is bundled with python: https://docs.python.org/3/library/venv.html

**Comment by bkabrda** [comment]
Yeah, this is obviously error on our side. I'll fix it, thanks for reporting.
